### PR TITLE
Fix `bin/list-all`

### LINKED ISSUE #142: Fresh install of asdf and asdf-ruby, 'list-all' shows git info, no versions
When I run `asdf list-all ruby` I get a bunch of git output, and no versions.  I tried uninstalling and reinstalling the plugin (included in this output)

```
> asdf plugin-remove ruby
> asdf plugin-add ruby
> asdf list-all ruby
Downloading ruby-build...
Cloning into 'ruby-build-source'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 9941 (delta 0), reused 0 (delta 0), pack-reused 9940
Receiving objects: 100% (9941/9941), 2.11 MiB | 11.53 MiB/s, done.
Resolving deltas: 100% (6449/6449), done.
Note: checking out 'v20191004'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at da8e0b4 Bump version to v20191004
> 
```

### PR DESCRIPTION
**Pull request by kassio**
Also, use `grep -v` (-v: Invert match) to remove the `topaz-dev` from
the results.

Fixes #142.

### CODE REVIEW

File: bin/list-all [hunk 1]
```diff
@@ -8,9 +8,7 @@ source "$(dirname $0)/../lib/utils.sh"
...
   ensure_ruby_build_setup
 
-  # This sed command was a quick and dirty solution to remove topaz-dev from
-  # the version list, since it doesn't exist
-  "$(ruby_build_path)" --definitions | paste -sd " " - | sed "s|topaz-dev||g"
+  "$(ruby_build_path)" --definitions | grep -v "topaz-dev" | paste -sd " " -
 }
 
-list_versions
+echo $(list_versions)
```
Comment (Stratus3D) [inline bin/list-all]: Did shellcheck complain about this line? I don't think the echo is needed here. Just `list_versions` should be enough.

Comment (kassio) [reply bin/list-all]: Actually, it complains:
```
$ shellcheck bin/list-all

In bin/list-all line 6:
source "$(dirname $0)/../lib/utils.sh"
       ^-----------------------------^ SC1091: Not following: ../lib/utils.sh was not specified as input (see shellcheck -x).
                  ^-- SC2086: Double quote to prevent globbing and word splitting.

Did you mean:
source "$(dirname "$0")/../lib/utils.sh"


In bin/list-all line 14:
echo $(list_versions)
     ^--------------^ SC2046: Quote this to prevent word splitting.
     ^--------------^ SC2005: Useless echo? Instead of 'echo $(cmd)', just use 'cmd'.

For more information:
  https://www.shellcheck.net/wiki/SC2046 -- Quote this to prevent word splitt...
  https://www.shellcheck.net/wiki/SC1091 -- Not following: ../lib/utils.sh wa...
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
```

But without it nothing is printed:

```
~/.asdf/plugins/ruby (master $ u=)
$ asdf list-all ruby
Downloading ruby-build...
Cloning into 'ruby-build-source'...
remote: Enumerating objects: 129, done.
remote: Counting objects: 100% (129/129), done.
remote: Compressing objects: 100% (89/89), done.
remote: Total 10073 (delta 73), reused 80 (delta 36), pack-reused 9944
Receiving objects: 100% (10073/10073), 2.15 MiB | 4.06 MiB/s, done.
Resolving deltas: 100% (6525/6525), done.
HEAD is now at f6e8dc1 ruby-build 20191102
/Users/kassio/.asdf/plugins/ruby/ruby-build-source
~/.asdf/plugins/ruby (master $ u=)
```

My shell:
```
$ zsh --version
zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0.0)
```

Comment (Stratus3D) [reply bin/list-all]: I think you need to direct STDERR to `/dev/null` to solve this. Try this instead:

```
list_versions 2> /dev/null
```

Comment (kassio) [reply bin/list-all]: Unfortunately it didn't work.

_HOME__asdf_plugins_ruby__zsh_

Comment (Stratus3D) [reply bin/list-all]: This works on my machine:

```
#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=../lib/utils.sh
source "$(dirname $0)/../lib/utils.sh"

list_versions() {
  ensure_ruby_build_setup

  # This sed command was a quick and dirty solution to remove topaz-dev from
  # the version list, since it doesn't exist
  "$(ruby_build_path)" --definitions | grep -v "topaz-dev" | paste -sd " " -
}

list_versions 2> /dev/null
```

It looks like you reverted your other change on line 11 when you tested that.

Comment (kassio) [reply bin/list-all]: Just to be sure, are you on zsh?

Comment (Stratus3D) [reply bin/list-all]: Yes I am, but those changes work for me in Zsh and Bash.

Comment (kassio) [reply bin/list-all]: Ok, I'll investigate why my shell is not working.

Changed the code to be like you suggested.

Comment (kassio) [reply bin/list-all]: So, it seems that my problem is related to `$CDPATH` which I suppose maybe a problem with `asdf` itself.

```console
~/.asdf/plugins/ruby (master u+1)
$ echo $CDPATH
.:/Users/kassio:/Users/kassio/src:/Users/kassio/.config:

~/.asdf/plugins/ruby (master u+1)
$ asdf list-all ruby
/Users/kassio/.asdf/plugins/ruby/ruby-build-source

~/.asdf/plugins/ruby (master u+1)
$ CDPATH="" asdf list-all ruby
1.8.5-p52
1.8.5-p113
1.8.5-p114
1.8.5-p115
1.8.5-p231
1.8.6
# ...
```

Comment (kassio) [reply bin/list-all]: On the other hand, [asdf elixir plugin works and it uses `echo`](https://github.com/asdf-vm/asdf-elixir/blob/master/bin/list-all).

File: lib/utils.sh [hunk 2]
```diff
@@ -29,21 +29,24 @@ ensure_ruby_build_installed() {
 download_ruby_build() {
     # Print to stderr so asdf doesn't assume this string is a list of versions
     echo "Downloading ruby-build..." >&2
-    local build_dir="ruby-build-source"
+    local build_dir="$(asdf_ruby_plugin_path)/ruby-build-source"
 
     # Clone down and checkout the correct ruby-build version
     git clone https://github.com/rbenv/ruby-build.git $build_dir >&2 >/dev/null
     (cd $build_dir; git checkout $RUBY_BUILD_TAG >&2 >/dev/null)
```
Comment (kassio) [inline lib/utils.sh]: The problem seems to be with this `cd` and my `CDPATH`.
My suggestion is to use the full path for the `ruby-build-source`.

File: bin/list-all (hunk 1 above)
Comment (Stratus3D) [reply bin/list-all]: Are you exporting `CDPATH` or just setting it? Because it can meddle with how the path is interpreted, and also cause `cd` to print to STDOUT, you should not export `CDPATH`. Here is what I have in my dotfiles - https://github.com/Stratus3D/dotfiles/blob/44678c7c645ae9a442b4fa246cfd39b9e4d0a74c/mixins/general#L28-L31

Comment (kassio) [reply bin/list-all]: I tried without exporting the CDPATH and still doesn't work on my environment.
What do you think of my proposal to use the full path for the `ruby-build-source`?

Comment (Stratus3D) [reply bin/list-all]: Full path should be fine.

**Comment by Stratus3D** [comment]
It looks like the build is failing on OSX.

**Comment by kassio** [comment]
The failure seems to be in the master branch, something wrong with:
```
Downloading truffleruby-19.2.0.1-macos-amd64.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/3a1bef2706ea9dc430f45ec0d7bf798ef09526f39d5102d88ef6a1b74bea3c12
Installing truffleruby-19.2.0.1...
/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/asdf.XXXX.wtCjSwiO/plugins/ruby/ruby-build/bin/ruby-build: line 750: ./lib/truffle/post_install_hook.sh: No such file or directory
BUILD FAILED (OS X 10.13.3 using ruby-build 20191111)
```

**Comment by Stratus3D** [comment]
Odd. I thought that was recently fixed. Thanks for the PR!
