### PR TITLE
Fix auto-reshim on bundle install and gem uninstall.

### LINKED ISSUE #63: Automatic reshim after gem installing/uninstalling
Hello!

It's weird that I should exec `asdf reshim ruby` after any gem installation and uninstallation.

So, I've ran `bundle`, which installed needed dependencies, but I can't exec `rspec`, for example.

Please.

### PR DESCRIPTION
**Pull request by djmarcin**
This fixes #63 but depends on https://github.com/rubygems/rubygems/pull/3534 being merged in order to actually work. There is a long-standing bug in bundler that prevents it from loading `rubygems_plugin.rb` from `RUBYLIB`. However, there is no problem having this hook exist with a version of bundler that doesn't support it -- this file will just never be evaluated in that case.

It also fixes shims not being removed on `gem uninstall` where installer.bin_dir is not set, so it can never match `Gem.default_bindir`. Additionally, the `#{RUBY_VERSION} bin/#{executable}` syntax does not work for removing shims, so in the interest of simplicity, the hook now just runs `asdf reshim ruby` which works in both the install and uninstall cases, but is potentially less efficient for installation via `gem install`.

### CODE REVIEW

File: rubygems-plugin/rubygems_plugin.rb [hunk 1]
```diff
@@ -1,11 +1,18 @@
...
+    `asdf reshim ruby`
   end
+end
 
+if defined?(Bundler::Installer)
+  Bundler::Installer.prepend ReshimInstaller
+else
+  maybe_reshim = lambda do |installer|
+    # If any gems with executables were installed or uninstalled, reshim.
+    `asdf reshim ruby` if installer.spec.executables.any?
```
Comment (Stratus3D) [inline rubygems-plugin/rubygems_plugin.rb:14]: Why not specify the `RUBY_VERSION` here?

Comment (Stratus3D) [reply rubygems-plugin/rubygems_plugin.rb:14]: I understand why the `bin/${executable}` part was removed, but the version might still be worth including.

Comment (djmarcin) [reply rubygems-plugin/rubygems_plugin.rb:14]: I'm not sure if this is a bug with asdf itself, but while the `#{RUBY_VERSION}` does seem to work after `gem install`, it does not remove the dead shim after `gem uninstall`.

With version:
```
$ gem install railties ; echo "Rails: $(which rails)" ; yes | gem uninstall --force railties; echo "Rails: $(which rails)"
Fetching railties-6.0.2.2.gem
Successfully installed railties-6.0.2.2
Parsing documentation for railties-6.0.2.2
Installing ri documentation for railties-6.0.2.2
Done installing documentation for railties after 0 seconds
1 gem installed
Rails: /Users/djmarcin/.asdf/shims/rails
Removing rails
Successfully uninstalled railties-6.0.2.2
Rails: /Users/djmarcin/.asdf/shims/rails
```

Without version:
```
$ gem install railties ; echo "Rails: $(which rails)" ; yes | gem uninstall --force railties; echo "Rails: $(which rails)"
Fetching railties-6.0.2.2.gem
Successfully installed railties-6.0.2.2
Parsing documentation for railties-6.0.2.2
Installing ri documentation for railties-6.0.2.2
Done installing documentation for railties after 0 seconds
1 gem installed
Rails: /Users/djmarcin/.asdf/shims/rails
Removing rails
Successfully uninstalled railties-6.0.2.2
Rails:
```

Although, since installs are likely more frequent than uninstalls, I could change the behavior to iterate over the binaries on install, and just reshim everything on uninstall.

Comment (djmarcin) [reply rubygems-plugin/rubygems_plugin.rb:21]: I've added the customized behavior for install & uninstall.

File: rubygems-plugin/rubygems_plugin.rb [hunk 2]
```diff
@@ -1,11 +1,23 @@
...
+module ReshimInstaller
+  def install(options)
+    super
+    # We don't know which gems were installed, so always reshim.
+    `asdf reshim ruby`
+  end
+end
 
-  if installer.spec.executables.any? && installer.bin_dir == Gem.default_bindir
+if defined?(Bundler::Installer)
```
Comment (Stratus3D) [inline rubygems-plugin/rubygems_plugin.rb:9]: If this is defined, wouldn't we still want the `Gem` hooks setup too? It doesn't seem like these two things are mutually exclusive.

Comment (djmarcin) [reply rubygems-plugin/rubygems_plugin.rb:9]: I believe that `Bundler::Installer` is only defined when the `bundle` command is running. While Bundler is operating, we wouldn't want the gem hooks to run because we want to batch one reshim operation at the end rather than after each Gem.
